# Dependabot configuration for spotify-mcp
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Monitor GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci(deps)"
      include: "scope"

  # Monitor Docker base images
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "build(deps)"
      include: "scope"

  # Monitor Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "build(deps)"
      include: "scope"
    # Group minor and patch updates together
    groups:
      dev-dependencies:
        patterns:
          - "pytest*"
          - "black"
          - "mypy"
          - "pylint"
          - "ruff"
        update-types:
          - "minor"
          - "patch"
      production-dependencies:
        patterns:
          - "spotipy"
          - "mcp"
          - "python-dotenv"
        update-types:
          - "minor"
          - "patch"

