# Configuration for release-drafter - https://github.com/release-drafter/release-drafter

name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '📚 Documentation'
    labels:
      - 'documentation'
      - 'docs'
  - title: '⚡ Performance'
    labels:
      - 'performance'
  - title: '🔒 Security'
    labels:
      - 'security'
  - title: '🧹 Maintenance'
    labels:
      - 'chore'
      - 'maintenance'
      - 'dependencies'
      - 'ci'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'minor'
      - 'feature'
  patch:
    labels:
      - 'patch'
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'chore'
      - 'dependencies'

autolabeler:
  - label: 'major'
    branch:
      - '/major.*/'
  - label: 'minor'
    branch:
      - '/feature.*/'
      - '/minor.*/'
  - label: 'patch'
    branch:
      - '/fix.*/'
      - '/patch.*/'
      - '/hotfix.*/'

exclude-labels:
  - 'skip-changelog'

replacers:
  - search: '/\(#(\d+)\)/'
    replace: '(#$1)'

sort: 'ASC'

collapsible: true

