# Configuration for probot-stale - https://github.com/probot/stale

# Number of days of inactivity before an issue or PR becomes stale
daysUntilStale: 60
daysUntilClose: 7

# Exempt issues and PRs with these labels from being marked as stale
exemptLabels:
  - pinned
  - security
  - enhancement
  - bug

# Label to use when marking as stale
staleLabel: stale

# Comment to post when marking as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs within 7 days.
  Thank you for your contributions.

# Comment to post when closing a stale issue or PR. Set to `false` to disable
closeComment: >
  This issue has been automatically closed due to inactivity. If you believe
  this issue is still relevant, please feel free to reopen it.

# Limit to only `issues` or `pulls`
only: issues

