name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: Import smoke test
        run: |
          python -c "import spotify_mcp.server; import spotify_mcp.tools; import spotify_mcp.config; print('✓ All imports OK')"

      - name: Build Docker image
        run: |
          docker build -t spotify-mcp:ci .
