name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    lint-test-build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install -e ".[dev,test]"

            - name: Import smoke test
              run: |
                  python -c "import spotify_mcp.server; import spotify_mcp.tools; import spotify_mcp.config; print('✓ All imports OK')"

            - name: Run tests with coverage
              run: |
                  pytest --cov=spotify_mcp --cov-report=xml --cov-report=term-missing

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v5
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  files: ./coverage.xml
                  flags: unittests
                  name: codecov-umbrella
                  fail_ci_if_error: false

            - name: Build Docker image
              run: |
                  docker build -t spotify-mcp:ci .
